// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.1.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['hyperelasticity.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

typedef double ufc_scalar_t;
#include "ufc.h"

#ifdef __cplusplus
extern "C" {
#endif

extern ufc_finite_element element_39c9f9a46a1e147d68060aea877cb63c830e361c;

extern ufc_finite_element element_4011c9fc5cab9d228bf83f781338bdef18a139a5;

extern ufc_dofmap dofmap_39c9f9a46a1e147d68060aea877cb63c830e361c;

extern ufc_dofmap dofmap_4011c9fc5cab9d228bf83f781338bdef18a139a5;

extern ufc_integral integral_6fc2135d69a175e7c7803863718016588feba4f7;

extern ufc_integral integral_7b25a736b6b967b80ad9d11b31bc933b7a2aa00c;

extern ufc_form form_bae4b5a79dee87e5739d9996ee85836f037ea976;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_hyperelasticity_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_hyperelasticity_F(const char* function_name);

extern ufc_form form_24d3f36c4ffbf5df1116a83311c4103f64f56034;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_hyperelasticity_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_hyperelasticity_J(const char* function_name);

#ifdef __cplusplus
}
#endif
