// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.1.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['SaintVenantKirchhoff_Hexa.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufc_finite_element element_2cd7e351a3784536603dc539e3fc14bf2e52b04b;

extern ufc_finite_element element_c73b62d5e887f3f65d505c31a9e46ea55490aeba;

extern ufc_dofmap dofmap_2cd7e351a3784536603dc539e3fc14bf2e52b04b;

extern ufc_dofmap dofmap_c73b62d5e887f3f65d505c31a9e46ea55490aeba;

extern ufc_integral integral_c006f6d53f4913541672dae98fc7e85b1a97d9be;

extern ufc_integral integral_2a7c92ceadc4878c99f36b40783e689a633f6968;

extern ufc_form form_46150171fccf01f8f9e10567888784aeec49d8c6;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_SaintVenantKirchhoff_Hexa_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_F(const char* function_name);

extern ufc_form form_5b37b345e368d17ce355b468d4ccd5f00fcf6dca;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_SaintVenantKirchhoff_Hexa_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_SaintVenantKirchhoff_Hexa_J(const char* function_name);

#ifdef __cplusplus
}
#endif
