// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.1.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['SaintVenantKirchhoff_Tetra.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufc_finite_element element_80a2770a78964cfabe9c4636ed5eb7bfd7da084e;

extern ufc_finite_element element_318b489bb75280c57850d36303832dd08d97207b;

extern ufc_dofmap dofmap_80a2770a78964cfabe9c4636ed5eb7bfd7da084e;

extern ufc_dofmap dofmap_318b489bb75280c57850d36303832dd08d97207b;

extern ufc_integral integral_82ebfb3b043a028d1e15129fce1aeecf49962468;

extern ufc_integral integral_3fe4ffdf543d5c59423df68d6e3b62ff65770439;

extern ufc_form form_6317f9fe459a7719c2d81d54cf2687c5a75ce4ac;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_SaintVenantKirchhoff_Tetra_F;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_SaintVenantKirchhoff_Tetra_F(const char* function_name);

extern ufc_form form_ef47b7de01532d0415825aa221175f7e03580fae;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_SaintVenantKirchhoff_Tetra_J;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_SaintVenantKirchhoff_Tetra_J(const char* function_name);

#ifdef __cplusplus
}
#endif
